### ISSUE TITLE
[Issue] Airline | Select payload incorrectly splits identical items into multiple entries and misassigns addon quantities

### ISSUE THREAD

**Issue by Priyankapndy** [ONDC-Official/automation-framework#295]
### Type of Issue

Question / Clarification

### Summary

When selecting multiple quantities of the same item with addons, the select call splits them into multiple individual item objects and assigns incorrect addon quantities — identical items with identical addons must be merged into a single item object with matching qtys.

### Expected Behavior

Identical items (same id, same price/attributes, and identical addons) should be merged into a single item object whose quantity equals the summed quantity and whose addon quantities align properly.

### Steps to Reproduce / Context

Steps to reproduce (STR)

On the UI, select Item I1 with quantity = 3 and addon A1 with quantity = 3.

Select Item I2 with quantity = 2 and addon A2 with quantity = 2.

Select Item I2 again with quantity = 2 and no addons.

Submit the purchase flow up to the /select call.

Capture the select payload (video attached demonstrates the issue).

### Payloads / Logs / Screenshots (if applicable)

https://drive.google.com/file/d/1OdEkIZg7SnxYNL5zXGjJZ4BxwO7SzQel/view?usp=sharing

### Domain

TRV 12 Airline 

### Version

2.0.0

### Reported By (GitHub Handle)

@priyanka_pndy

**Comment by sourabhsaini11** [comment]
@Priyankapndy, above issues are fixed on dev. Kindly check.

**Comment by Priyankapndy** [comment]
[Purchase Journey(Code Based Flow)-Purchase Journey(Code Based Flow).json](https://github.com/user-attachments/files/24883826/Purchase.Journey.Code.Based.Flow.-Purchase.Journey.Code.Based.Flow.json)
@sourabhsaini11 Still not fixed , same issue
