### ISSUE TITLE
[Issue] TRV 14 | NP is stuck as init is not been received FLow - Purchase Journey without form

### ISSUE THREAD

**Issue by Priyankapndy** [ONDC-Official/automation-framework#307]
### Type of Issue

Question / Clarification

### Summary

Transaction id - 37eacc9a-e0dc-44bd-972e-5bd06ad02dc4",
    "bpp_id": "dev-booking.tripxoxo.com",
    "bpp_uri": "https://dev-booking.tripxoxo.com"

### Payloads / Logs / Screenshots (if applicable)

{
  "context": {
    "action": "on_select",
    "bap_id": "staging-automation.ondc.org",
    "bap_uri": "https://workbench.ondc.tech/api-service/ONDC:TRV14/2.0.0/buyer",
    "domain": "ONDC:TRV14",
    "location": {
      "city": {
        "code": "std:011"
      },
      "country": {
        "code": "IND"
      }
    },
    "message_id": "716b5e82-a8d6-4a6a-9d8f-7444b7143ab0",
    "timestamp": "2025-12-10T13:27:39.655Z",
    "transaction_id": "37eacc9a-e0dc-44bd-972e-5bd06ad02dc4",
    "ttl": "PT30S",
    "version": "2.0.0",
    "bpp_id": "dev-booking.tripxoxo.com",
    "bpp_uri": "https://dev-booking.tripxoxo.com"
  },
  "message": {
    "order": {
      "provider": {
        "id": "7cf71526-82a3-4b84-9e54-77ced53960d1",
        "descriptor": {
          "name": "By riluvan",
          "images": [
            {
              "url": "https://tripxoxo-prod.s3.amazonaws.com/tripxoxo_prod/documents/Top_Destination_Dubai_0o48kC8.png",
              "size_type": "md"
            }
          ]
        },
        "locations": [
          {
            "id": "L-5ea9c610-e6b2-4547-b6fa-da5050d4d3c4",
            "gps": "17.00737,17.0057",
            "descriptor": {
              "name": "ondc-test",
              "short_desc": "ondc-test"
            }
          }
        ]
      },
      "fulfillments": [
        {
          "id": "F-7cf71526-82a3-4b84-9e54-77ced53960d1",
          "stops": [
            {
              "type": "START",
              "time": {
                "timestamp": "2025-12-10T07:57:36.000Z"
              }
            }
          ],
          "type": "VISIT",
          "vehicle": {
            "category": "SITE"
          }
        }
      ],
      "items": [
        {
          "id": "cd8ce8c6-dbf1-47dc-9f8f-f11c1ed7ed98",
          "descriptor": {
            "name": "adult",
            "code": "ABSTRACT",
            "images": [
              {
                "url": "https://trip-dev.s3.amazonaws.com/tripxoxo_dev/documents/relax1.png",
                "size_type": "md"
              }
            ],
            "short_desc": "<p>sdasd</p>",
            "long_desc": "<p>sdasd</p>"
          },
          "location_ids": [
            "L-5ea9c610-e6b2-4547-b6fa-da5050d4d3c4"
          ],
          "category_ids": [
            "C-cd8ce8c6-dbf1-47dc-9f8f-f11c1ed7ed98"
          ],
          "fulfillment_ids": [
            "F-7cf71526-82a3-4b84-9e54-77ced53960d1"
          ],
          "time": {
            "label": "VALIDITY",
            "duration": "P2D"
          }
        },
        {
          "id": "cd8ce8c6-dbf1-47dc-9f8f-f11c1ed7ed98_$2202f830-ce4b-495e-bd37-d5eb36ad2070$20251214$_20251214",
          "parent_item_id": "cd8ce8c6-dbf1-47dc-9f8f-f11c1ed7ed98",
          "descriptor": {
            "code": "ENTRY_PASS",
            "name": "adult - adult&nbsp;(1-99) (2025-12-14 to 2025-12-14)",
            "images": [
              {
                "url": "https://dev-admin.tripxoxo.com/assets/images/tripxoxo_white_bg.png",
                "size_type": "md"
              }
            ],
            "short_desc": "<p>sdasd</p>",
            "long_desc": "<p>sdasd</p>"
          },
          "location_ids": [
            "L-5ea9c610-e6b2-4547-b6fa-da5050d4d3c4"
          ],
          "fulfillment_ids": [
            "F-7cf71526-82a3-4b84-9e54-77ced53960d1"
          ],
          "price": {
            "currency": "INR",
            "value": "200.00"
          },
          "quantity": {
            "selected": {
              "count": 3
            }
          }
        },
        {
          "id": "cd8ce8c6-dbf1-47dc-9f8f-f11c1ed7ed98_$d259337f-8d2d-42bc-9172-c488668fd789$20251214$_20251214",
          "parent_item_id": "cd8ce8c6-dbf1-47dc-9f8f-f11c1ed7ed98",
          "descriptor": {
            "code": "ENTRY_PASS",
            "name": "adult - child&nbsp;(1-99) (2025-12-14 to 2025-12-14)",
            "images": [
              {
                "url": "https://dev-admin.tripxoxo.com/assets/images/tripxoxo_white_bg.png",
                "size_type": "md"
              }
            ],
            "short_desc": "<p>sdasd</p>",
            "long_desc": "<p>sdasd</p>"
          },
          "location_ids": [
            "L-5ea9c610-e6b2-4547-b6fa-da5050d4d3c4"
          ],
          "fulfillment_ids": [
            "F-7cf71526-82a3-4b84-9e54-77ced53960d1"
          ],
          "price": {
            "currency": "INR",
            "value": "200.00"
          },
          "quantity": {
            "selected": {
              "count": 4
            }
          }
        }
      ],
      "cancellation_terms": [
        {
          "cancellation_eligible": true,
          "cancellation_fee": {
            "percentage": "0"
          },
          "cancel_by": {
            "label": "DURATION",
            "duration": "PT24H"
          }
        }
      ],
      "replacement_terms": [
        {
          "external_ref": {
            "mimetype": "text/html",
            "url": "https://dev-booking.tripxoxo.com/ondc/replacement.html"
          }
        }
      ],
      "quote": {
        "breakup": [
          {
            "title": "BASE_FARE",
            "item": {
              "id": "cd8ce8c6-dbf1-47dc-9f8f-f11c1ed7ed98_$2202f830-ce4b-495e-bd37-d5eb36ad2070$20251214$_20251214",
              "price": {
                "currency": "INR",
                "value": "200.00"
              },
              "quantity": {
                "selected": {
                  "count": 3
                }
              }
            },
            "price": {
              "currency": "INR",
              "value": "600.00"
            }
          },
          {
            "title": "BASE_FARE",
            "item": {
              "id": "cd8ce8c6-dbf1-47dc-9f8f-f11c1ed7ed98_$d259337f-8d2d-42bc-9172-c488668fd789$20251214$_20251214",
              "price": {
                "currency": "INR",
                "value": "200.00"
              },
              "quantity": {
                "selected": {
                  "count": 4
                }
              }
            },
            "price": {
              "currency": "INR",
              "value": "800.00"
            }
          }
        ],
        "price": {
          "currency": "INR",
          "value": "1400.00"
        }
      }
    }
  }
}

![Image](https://github.com/user-attachments/assets/2636629d-5fd6-4e18-8c9c-b3347758a293)

### Domain

TRV 14

### Version

2.0.0

### Reported By (GitHub Handle)

@Priyanka_pndy

**Comment by y0geshb** [comment]
@sourabhsaini11 
[log.json](https://github.com/user-attachments/files/24096086/log.json) 
In the payload we noticed that the NP is sending values containing HTML tags, for example <p>sdasd</p>. Can you check whether this is causing the issue? 

If this is the root cause, then the payload should have been NACKed in the response

<img width="524" height="129" alt="Image" src="https://github.com/user-attachments/assets/70b0a132-1161-4fe1-af8b-6198cbdacf1a" />

**Comment by sharique827** [comment]
@y0geshb ,

Flow issue has been fixed, Its now running, And you can test

**Comment by Priyankapndy** [comment]
@sharique827 Have u deployed this on WB https://workbench.ondc.tech/scenario

As NP has raised this issue and we cant test this on dev

**Comment by sharique827** [comment]
@Priyankapndy ,
Yes deployed to staging server

**Comment by Priyankapndy** [comment]
@sharique827  Np is still facing same issue even after removing tags from short desc , long desc . Pl check

**Comment by sharique827** [comment]
@Priyankapndy 

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/2d6a2e64-fca4-4fc0-a97d-0d452f4d579f" />

Its working,

Or we can have a call with NP on monday

**Comment by sharique827** [comment]
@Priyankapndy / @Rishabh-ondc ,

Can we ask NP to connect.

**Comment by Priyankapndy** [comment]
@sharique827 Yes NP will connect today at 3 pm

**Comment by Priyankapndy** [comment]
@sharique827 This is latest on_select logs please let us know once it is resolved 
https://codeshare.io/5QlPBW

**Comment by sharique827** [comment]
@Priyankapndy 
We are checking the logs

**Comment by Priyankapndy** [comment]
We have resolve this issue over call and NP confirmed on whatsapp grp for same hence closing
